package ult.nodo.ciencia.excepcion;

public class UsuarioException extends GeneralException {

    public UsuarioException(Throwable cause) {
        super(cause);
    }
}
